# Generated by Django 5.2.11 on 2026-02-28 05:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CredibilityScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.IntegerField(help_text='0-100')),
                ('confidence_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10)),
                ('breakdown', models.JSONField(default=dict, help_text='Transparent score breakdown: activity, consistency, longevity, etc.')),
                ('flags', models.JSONField(default=list, help_text='Quality/anomaly flags')),
                ('insights', models.JSONField(default=list, help_text='Insight cards')),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='core.businessprofile')),
            ],
            options={
                'db_table': 'credibility_scores',
                'ordering': ['-computed_at'],
                'get_latest_by': 'computed_at',
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('whatsapp', 'Whatsapp'), ('telegram', 'Telegram'), ('instagram', 'Instagram'), ('csv_grab', 'Csv Grab'), ('csv_shopee', 'Csv Shopee'), ('csv_foodpanda', 'Csv Foodpanda'), ('pdf_bank', 'Pdf Bank'), ('pdf_ewallet', 'Pdf Ewallet'), ('screenshot', 'Screenshot'), ('manual', 'Manual'), ('voice', 'Voice')], max_length=20)),
                ('file_url', models.URLField(blank=True, default='', max_length=500)),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('file_size', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('QUEUED', 'Queued'), ('EXTRACTED', 'Extracted'), ('NORMALIZED', 'Normalized'), ('ANALYZED', 'Analyzed'), ('REPORTED', 'Reported'), ('FAILED', 'Failed')], default='UPLOADED', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='core.businessprofile')),
            ],
            options={
                'db_table': 'evidence',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_time', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='MYR', max_length=3)),
                ('channel', models.CharField(choices=[('whatsapp', 'Whatsapp'), ('grabfood', 'Grabfood'), ('shopee', 'Shopee'), ('foodpanda', 'Foodpanda'), ('lazada', 'Lazada'), ('tng', 'Tng'), ('bank', 'Bank'), ('cash', 'Cash'), ('other', 'Other')], max_length=20)),
                ('event_type', models.CharField(choices=[('order', 'Order'), ('payment', 'Payment'), ('payout', 'Payout'), ('refund', 'Refund')], max_length=20)),
                ('confidence', models.FloatField(default=0.0, help_text='Confidence score 0.0 - 1.0')),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='core.businessprofile')),
                ('source_evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='evidence.evidence')),
            ],
            options={
                'db_table': 'ledger_entries',
                'ordering': ['-event_time'],
            },
        ),
        migrations.CreateModel(
            name='EventLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('link_type', models.CharField(choices=[('amount_match', 'Amount Match'), ('time_match', 'Time Match'), ('keyword_match', 'Keyword Match'), ('cross_channel', 'Cross Channel')], max_length=20)),
                ('similarity_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_as_a', to='evidence.ledgerentry')),
                ('entry_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_as_b', to='evidence.ledgerentry')),
            ],
            options={
                'db_table': 'event_links',
            },
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['business', 'event_time'], name='ledger_entr_busines_240a56_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['business', 'channel'], name='ledger_entr_busines_a189e1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventlink',
            unique_together={('entry_a', 'entry_b')},
        ),
    ]
