# Generated by Django 5.2.11 on 2026-02-28 05:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('channels', models.JSONField(default=list, help_text='List of active channels')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'business_profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_mode', models.CharField(choices=[('private', 'Private'), ('token_only', 'Token Only'), ('public', 'Public')], default='token_only', max_length=20)),
                ('redact_pii', models.BooleanField(default=True)),
                ('store_raw_files', models.BooleanField(default=True)),
                ('risk_disclosure_accepted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consent', to='core.businessprofile')),
            ],
            options={
                'db_table': 'consent_settings',
            },
        ),
    ]
